# Generated by Django 3.0.8 on 2021-03-29 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('comments', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_no', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('unit_price', models.IntegerField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.Material')),
                ('supplier_company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('update_date', models.DateField(auto_now=True)),
                ('update_by', models.CharField(max_length=200)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.Material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SiteManageger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('is_approve', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('site_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=200)),
                ('due', models.CharField(max_length=200)),
                ('supply_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.Supply')),
            ],
        ),
    ]
