# Generated by Django 3.0.8 on 2021-03-29 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('emergency_contact', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nid_number', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('landarea', models.CharField(max_length=200)),
                ('rajuk_no', models.CharField(max_length=200)),
                ('architect_name', models.CharField(max_length=200)),
                ('architect_reg_no', models.CharField(max_length=200)),
                ('starting_date', models.CharField(max_length=200)),
                ('end_date', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('nid_number', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LabourTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_types', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LabourWorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('consturction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.ConstructionSite')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.Labour')),
            ],
        ),
        migrations.CreateModel(
            name='StockManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('construct_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.ConstructionSite')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.Material')),
            ],
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='SiteManageger',
        ),
        migrations.AddField(
            model_name='labour',
            name='labour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_management.LabourTypes'),
        ),
    ]
