# Generated by Django 3.0.8 on 2021-03-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0002_auto_20210329_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
