# Generated by Django 3.0.8 on 2021-03-30 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0003_auto_20210329_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
