# Generated by Django 3.1.6 on 2021-04-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0004_labour_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmanagement',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
