# Generated by Django 3.1.6 on 2021-04-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0005_auto_20210411_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourworktime',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
