# Generated by Django 3.1.6 on 2021-04-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0006_auto_20210411_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourworktime',
            name='end_date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='labourworktime',
            name='start_date',
            field=models.CharField(max_length=200),
        ),
    ]
