# Generated by Django 3.1.6 on 2021-04-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0007_auto_20210411_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourworktime',
            name='end_date',
            field=models.CharField(max_length=200),
        ),
    ]
