# Generated by Django 3.1.6 on 2021-04-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_management', '0008_auto_20210411_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.CharField(max_length=200),
        ),
    ]
